version: 2
jobs:
  e2e:
    docker:
      - image: node:8
    steps:
      - checkout
      - run: yarn install
      - run: yarn e2e
workflows:
  version: 2
  e2e_workflow:
    triggers:
      - schedule:
          cron: '0 0-23\/3 * * *'
          filters:
            branches:
              only:
                - master
    jobs:
      - e2e
