name: Main
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 12
        uses: actions/setup-node@master
        with:
          node-version: 12
      - name: install
        run: |
          yarn install
      - name: test
        run: |
          yarn test
        env:
          CI: true
